### ISSUE TITLE
It worked with Firebase Cloud Functions!

### ISSUE THREAD

**Issue by 1amageek** [carson-katri/SwiftWebUI#1]
https://salada-f825d.web.app/

Thanks for the great work.
I used this project to run the SwiftUI with Firebase Cloud Functions.

**Comment by carson-katri** [comment]
Is there a GitHub project I can add to the Readme as an example of how to set this up?

**Comment by 1amageek** [comment]
https://github.com/1amageek/SwiftWebUI-WASM-CFs

**Comment by carson-katri** [comment]
I added this as an example in the Readme. I'm also going to look into adding this as a template for swiftwebui-scripts.
